### ISSUE TITLE
Implement document query service

### ISSUE THREAD

**Issue by fmatthies** [Onto-Med/top-backend#149]
Analogous to `PhenotypeQueryService` there needs to be a document query service that bridges the gap between frontend query generation and `top-document-query`.

-  How do we display/store the documents found?

**Comment by fmatthies** [comment]
Would it be feasible/in line with TOP to have some sort of document viewer page/component (that could be used by the document exploration section via the concept clusters as well) that can display the document information from the ES instance?

**Comment by ChristophB** [comment]
This sounds like a good feature.

How could the information available in ES be propagated to the frontend? In case of concept queries, there might be multiple ES instances and the frontend does not know any of them.
