### ISSUE TITLE
Move CSVConverter

### ISSUE THREAD

**Issue by fmatthies** [Onto-Med/top-backend#160]
Is there a way we could move all the CSV logic into  `top-backend` and `abstract` it? Right now I'm duplicating most of the code from `top-phenotypic-query` in `top-document-query`, because I want to provide some ability to store/save document query info.

**Comment by ChristophB** [comment]
I think we cannot create abstract classes/interfaces in `top-backend`, as this would lead to circular references.

**Comment by AlexU75** [comment]
Do you want to save the query specification as CSV, not as JSON?

**Comment by fmatthies** [comment]
> I think we cannot create abstract classes/interfaces in top-backend, as this would lead to circular references.
I figured; so the only option (if we wanted to pull it out either way), would be to make it into a separate package...

**Comment by fmatthies** [comment]
> Do you want to save the query specification as CSV, not as JSON?

Hm, I thought the metadata information would be feasible to have as csv as well.

**Comment by AlexU75** [comment]
Okay, then we'll have to outsource it.

**Comment by fmatthies** [comment]
we agreed on not outsourcing it; top-document-query features its own csv classes
