### ISSUE TITLE
Support multiple document sources

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/top-backend#197]
Currently, it is not possible to connect to multiple document sources. Only the default adapter configuration is used, others are ignored.

It seems like this is related to using `sping-boot-starter-data-elasticsearch` and modifications to the configuration, which are only performed on startup of the framework.

**Comment by ChristophB** [comment]
Ideally, the backend does not need any Elasticsearch dependencies. Connection to document sources should be handled by `top-document-query` or some other module.

**Comment by ChristophB** [comment]
In contrast to Elasticsearch, it seems like we definitely need Neo4J in the backend, because clusters are stored there and are part of the TOP main business model.

**Comment by ChristophB** [comment]
I created an issue in `top-document-query` that addresses outsourcing of concept cluster related stuff. See: https://github.com/Onto-Med/top-document-query/issues/9

**Comment by ChristophB** [comment]
Some notes:

* Because Neo4J is used to store the document related business model, we should remove Neo4J from `top-document-query`.
* That module only returns documents or graphs.
* The backend stores the graphs in a single Neo4J instance => only one configuration, no messing around with Spring properties.
* As we want to store multiple graphs from different document sources, all nodes need an additional property that indicates to which data source they belong.

**Comment by fmatthies** [comment]
Some other notes:

- [ ] Remove/adapt DocumentQuery configurations
- [ ] Remove ElasticsearchConfigBean
