### ISSUE TITLE
Elasticsearch health check failed

### ISSUE THREAD

**Issue by fmatthies** [Onto-Med/top-backend#207]
There is no (overt) elasticsearch spring dependency anymore in the backend, but it still runs the healthcheck.

**Comment by fmatthies** [comment]
> **[fmatthies]**
Okay, but this means that the spring-boot-starter-parent still has the elasticsearch-rest-client as a dependency. It shouldn't be in there anymore, as all the ES logic is in the top-document-query.
> **[ChristophB]**
spring-boot-starter-parent only enforces the version of elasticsearch-rest-client, in case the dependency is used at all.
> **[fmatthies]**
Hm, could this also be why the health check is still run (https://github.com/Onto-Med/top-backend/issues/207) even if the top-backend only has elasticsearch as a transitive dependency?
> **[ChristophB]**
Yes this could be the reason, because the Spring framework detects the transitive dependency and decides to perform the check - at least that is my guess.

**Comment by ChristophB** [comment]
This could be of help: https://www.baeldung.com/spring-boot-health-indicators#2-disabling-the-indicator

**Comment by fmatthies** [comment]
Seems to work... I was sure I tried something like that once.
